name: ci

on:
 push:

jobs:
  uv-tests:
    name: uv
    runs-on: ubuntu-latest

    steps:

     - name: Install uv
       uses: astral-sh/setup-uv@v3

     - name: run pre-commit
       run: uv run pre-commit run -a

     - name: Run tests
       run: uv run python -m unittest
