name: ci

on:
 push:

uv-example:
    name: python
    runs-on: ubuntu-latest
    strategy:
     matrix:
      python-version:
      - "3.10"
      - "3.11"
      - "3.12"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: run pre-commit
        run: uv run pre-commit run -a

      - name: Run tests
        run: uv run python -m unittest
